---
#
# Author: Walter Karl
# Date: September.2023
# Company: 
#
# Prerequisites
# ansible-galaxy collection install containers.podman
# ansible-galaxy collection install community.general
# ansible-galaxy collection install ansible.posix
# ansible-galaxy collection install community.mongodb
# ansible-galaxy collection install prometheus.prometheus
#
#
- name: Manage Home Infrastructure
  hosts: all # target server are selected by '-l svr-*' on CLI
  strategy: free
  #
  # vars_files:
  #   - './global_vars/defvars.yml'
  #
  gather_facts: true
  #  
  # vars:
  #   domain: home.lcl
  #
  # module_defaults:
  #   uri:
  #     validate_certs: no
  #     body_format: json
  #     status_code: 200, 201
  #     return_content: yes
  #
  roles:
    ###############################################
    # podman container management
    # all tasks run with 'ansible_become: true'
    # if a task needs to run as myadmin 'ansible_become=false' on CLI with '--extra_var'
    ###############################################
    - role: mgmt_SymconContainer
      when: v_role == "symcon"
    - role: mgmt_UnifiContainer # depreciated
      when: v_role == "unifi"
    - role: mgmt_SemaphoreContainer
      when: v_role == "semaphore"
    - role: mgmt_RunDeck
      when: v_role == "rundeck"
    # - role: mgmt_UptimeKuma
    #   when: v_role == "kuma"
    - role: mgmt_PrometheusGrafana
      when: v_role == "promgraf"
    - role: mgmt_Infrastructure
      when: v_role == "infra"
    ###############################################
    # Prometheus collection contain already roles
    # more information > https://prometheus-community.github.io/ansible/branch/main/index.html
    ###############################################
    - role: prometheus.prometheus.node_exporter
      vars:
        node_exporter_web_telemetry_path: "/metrics"
        node_exporter_web_listen_address: "0.0.0.0:9100"
        # node_exporter_version: "1.7.0"
        node_exporter_textfile_dir: "/var/lib/node_exporter"
        node_exporter_system_user: "node-exp"
        node_exporter_system_group: "node-exp"
        # node_exporter_enabled_collectors: ["systemd", {"textfile": {"directory": "{{ node_exporter_textfile_dir }}"}}]
        # node_exporter_binary_url: "https://github.com/{{ _node_exporter_repo }}/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-{{ go_arch }}.tar.gz"
        # node_exporter_checksums_url: "https://github.com/{{ _node_exporter_repo }}/releases/download/v{{ node_exporter_version }}/sha256sums.txt"
        node_exporter_binary_install_dir: "/usr/local/bin"      
      when: v_role == "promne"
    ###############################################
    # physical or virtual deployment
    ###############################################
    - role: mgmt_Wazuh
      # delegate_to: svr-toolz
      # delegate_facts: true
      # delegate_to: svr-unifi
      # delegate_to: svr-symcon
      vars:
        ansible_user: myadmin
        ansible_ssh_private_key_file: /home/myadmin/.ssh/id_rsa
        ansible_become: true
        ansible_become_user: root
        ansible_become_password: S#55ic#jA
      when: v_role == "wazuh"
    # - role: mgmt_FilesDirs
    #   when: v_role == "files"
#
#
#      
    #################################################
    # This solution is bullshit
    #################################################
    # - role: mgmt_Guacamole
    #   delegate_to: localhost
    #   vars:
    #     ansible_user: myadmin
    #     ansible_ssh_private_key_file: /home/myadmin/.ssh/id_rsa
    #     ansible_become: true
    #     ansible_become_user: root
    #     ansible_become_password: S#55ic#jA
    #   when: v_role == "guacamole"
