ansible_port: 22
ansible_connection: ansible.builtin.ssh
ansible_user: myadmin
ansible_ssh_private_key_file: /home/myadmin/.ssh/id_rsa
ansible_become: true
ansible_become_user: root
ansible_become_password: S#55ic#jA