api:
  dashboard: true
  insecure: true
  debug: true
entryPoints:
  web:
    address: ":80"
    # http:
    #   redirections:
    #     entryPoint:
    #       to: websecure
    #       scheme: https
    #       permanent: true
  websecure:
    address: ":443"

providers:
  file:
    filename: /etc/traefik_prov.yml
    watch: true

log:
  level: DEBUG # (Default: error) DEBUG, INFO, WARN, ERROR, FATAL, PANIC
  filePath: /var/log/traefik.log
accessLog:
  filePath: /var/log/traefik.log
  bufferingSize: 500
  # filters:
  #   statusCodes:
  #     - "400-499"