http:
  tls:
    insecureSkipVerify: true
  routers: 
    allbackendRouter:
      rule: HostRegexp(`senseg{id:[0-9][0-9]}`)
      service: allbackend
  services:
    allbackend:
      loadBalancer:
        servers:
          - url: 'https:/192.168.100.50'
          - url: 'https:/192.168.100.52'
          # - url: 'https:/senseg01.demo.lab'
          # - url: 'https:/senseg02.demo.lab'