http:
  routers: 
    sensegXXRouter:
      entryPoints:
        - 'web'
        # - 'websecure'
      rule: "Host(`senseg.demo.lab`)"
      service: sensegXX
    rbmRouter:
      entryPoints:
        - 'web'
      rule: "Host(`svr-rbm.home.rp.lcl`)"
      service: rbm
    symconRouter:
      entryPoints:
        - 'web'
      # rule: "HostRegexp(`svr-symcon.home.rp.lcl{all:.*}`) && Path(`/console{all:.*}`)"
      rule: "Host(`svr-symcon.home.rp.lcl`)"
      service: symcon
  services:
    sensegXX:
      loadBalancer:
        servers:
          - url: "https://senseg01.demo.lab/"
          - url: "https://senseg02.demo.lab/"
        serversTransport: ignoreCertTransport
    rbm:
      loadBalancer:
        servers:
          - url: 'https://svr-rbm.home.lcl'
        serversTransport: ignoreCertTransport
    symcon:
      loadBalancer:
        servers:
          - url: "http://svr-symcon.home.lcl:3777/console/"
        
  serversTransports:
    ignoreCertTransport:
      insecureSkipVerify: true
