api:
  dashboard: true
  insecure: true
entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: ":443"
    proxyProtocol:
      insecure: true
    http:
      #  tls:
      #   options:
      #     default:
      #       clientAuth:
      #         clientAuthType: NoClientCert
        


providers:
  file:
    filename: /etc/traefik_prov.yml
    watch: true
    
log:
  level: DEBUG # (Default: error) DEBUG, INFO, WARN, ERROR, FATAL, PANIC

