---
# tasks file for mgmt_RunDeck
#
# Author: Walter Karl
# Date: December.2023
# Company:
#
#
################################################
#
#################################################
- name: Create container network task
  block:
    - name: Create container network section
      containers.podman.podman_network:
        name: rundeck_net
      become: true
  tags:
    - crtMariaDB
    - crtRunDeck
#################################################
#
# ansible-playbook ./pb.mgmtHomeInfrastructure.yml --extra-vars "v_role=rundeck" --tags delImage
#
#################################################
# - name: Delete image file task
#   block:
#     - name: Delete image file section 
#       containers.podman.podman_network:
#         name: docker.io/mariadb
#         state: absent
#   # Tags
#   tags:
#     - delImage
#     - updMariaDB
#################################################
#
# ansible-playbook ./pb.mgmtHomeInfrastructure.yml --extra-vars "v_role=rundeck" --tags crtMariaDB
#
#################################################
- name: Create runDeck MariaDB container task
  block:
    - name: Create rundeck MariaDB container section
      containers.podman.podman_container:
        name: c_mdb_rundeck
        image: docker.io/mariadb:10
        hostname: svr-mdb_rundeck
        volumes:
          - rundeck-mysql:/var/lib/mysql
        ports:
          - 3306:3306
        network:
          - rundeck_net
        env:
          MARIADB_RANDOM_ROOT_PASSWORD: 'yes'
          MARIADB_DATABASE: rundeck
          MARIADB_USER: rundeck
          MARIADB_PASSWORD: S#55ic#jA
        debug: false
        restart_policy: on-failure:3
        state: started
      register: MariaDBOutputStart
    - name: Print MariaDBOutputStart
      debug:
        msg:
          - "<<<<< Output >>>>>"
          - "{{ MariaDBOutputStart }}"
        verbosity: 0
# Tags
  tags:
    - crtMariaDB
    - updMariaDB
#################################################
#
# ansible-playbook ./pb.mgmtHomeInfrastructure.yml --extra-vars "v_role=rundeck" --tags crtRunDeck
#
#################################################
# To install ansible follow this instructions:
# https://docs.ansible.com/ansible/latest/installation_guide/installation_distros.html#installing-ansible-on-debian
# prerequisites DONE - ansible still needs to be installed manually
#################################################
# git and pssh has to be installed as well - DONE
#################################################
# How to use podman commit
# https://www.techrepublic.com/article/create-custom-images-podman/
#################################################
- name: Create runDeck  container task
  block:
    - name: Create rundeck  container section
      containers.podman.podman_container:
        name: c_rundeck
        image: docker.io/rundeck/rundeck:5.0.0
        hostname: svr-rundeck
        volumes:
          - rundeck-data:/home/rundeck/server/data
          - rundeck-plugins:/home/rundeck/repository/installedPlugins
          - /home/myadmin/ansible:/home/rundeck/projects
        ports:
          - 4440:4440
        network:
          - rundeck_net
        env:
            RUNDECK_DATABASE_DRIVER: org.mariadb.jdbc.Driver
            RUNDECK_DATABASE_USERNAME: rundeck
            RUNDECK_DATABASE_PASSWORD: S#55ic#jA
            RUNDECK_DATABASE_URL: jdbc:mysql://c_mdb_rundeck/rundeck?autoReconnect=true&useSSL=false
            RUNDECK_GRAILS_URL: http://192.168.1.210:4440
        debug: true
        requires: 
          - c_mdb_rundeck
        restart_policy: on-failure:3
        state: started
    - name: Install Git, pssh section
      ansible.builtin.command:
        cmd: "{{ item }}"
      loop:
        - podman exec --user root c_rundeck apt update -y
        - podman exec --user root c_rundeck apt install git -y
        - podman exec --user root c_rundeck apt install pssh -y
        - podman exec --user root c_rundeck wget -O file.key  "https://keyserver.ubuntu.com/pks/lookup?fingerprint=on&op=get&search=0x6125E2A8C77F2818FB7BD15B93C4A3FD7BB9C367"
        - podman exec --user root c_rundeck gpg --dearmour -o /usr/share/keyrings/ansible-archive-keyring.gpg file.key
        - podman exec --user root c_rundeck echo "deb [signed-by=/usr/share/keyrings/ansible-archive-keyring.gpg] http://ppa.launchpad.net/ansible/ansible/ubuntu jammy main" | tee /etc/apt/sources.list.d/ansible.list
        - podman exec --user root c_rundeck rm -f file.key
      # args:
      #   chdir: ./
# Tags
  tags:
    - crtRunDeck

