---
# tasks file for mgmt_PrometheusGrafana
#
# Author: Walter Karl
# Date: December.2023
# Company:
#
#
################################################
#
#################################################
- name: Create container network task
  block:
    - name: Create container network section
      containers.podman.podman_network:
        name: promgraf_net
      become: true
  tags:
    - crtPrometheus
    - crtPromNodeExp
    - crtDNS
#################################################
#
# ansible-playbook ./pb.mgmtHomeInfrastructure.yml --extra-vars "v_role=promgraf" --tags crtPrometheus
#
#################################################
- name: Create Prometheus container task
  block:
    - name: Create Prometheus container section
      containers.podman.podman_container:
        name: c_prometheus
        image: docker.io/prom/prometheus
        hostname: svr-prometheus
        command:
          - '--config.file=/etc/prometheus/prometheus.yml'
          - '--storage.tsdb.path=/prometheus'
          - '--web.console.libraries=/usr/share/prometheus/console_libraries'
          - '--web.console.templates=/usr/share/prometheus/consoles'
        volumes:
          - /home/myadmin/ansible/roles/mgmt_PrometheusGrafana/files/prometheus.yml:/etc/prometheus/prometheus.yml
          - prometheus_data:/prometheus
        ports:
          - 9095:9090 # cockpit uses 9090 already
        network:
          - promgraf_net
        # env:
        #   MARIADB_RANDOM_ROOT_PASSWORD: 'yes'
        debug: false
        restart_policy: on-failure:3
        state: started
      register: PrometheusOutput
    - name: Print PrometheusOutput
      debug:
        msg:
          - "<<<<< Output >>>>>"
          - "{{ PrometheusOutput }}"
        verbosity: 0
# Tags
  tags:
    - crtPrometheus
#################################################
#
# ansible-playbook ./pb.mgmtHomeInfrastructure.yml --extra-vars "v_role=promgraf" --tags crtPrometheus
#
#################################################
- name: Create Grafana container task
  block:
    - name: Create Grafana container section
      containers.podman.podman_container:
        name: c_grafana
        image: docker.io/grafana/grafana
        hostname: svr-grafana
        volumes:
          - gf_data:/var/lib/grafana
          - gf_provisioning:/etc/grafana/provisioning
        ports:
          - 3000:3000
        network:
          - promgraf_net
        env:
          GF_SECURITY_ADMIN_USER: admin
          GF_SECURITY_ADMIN_PASSWORD: admin
          GF_INSTALL_PLUGINS: 'grafana-clock-panel,grafana-simple-json-datasource'
        debug: false
        restart_policy: on-failure:3
        state: started
      register: GrafanaOutput
    - name: Print GrafanaOutput
      debug:
        msg:
          - "<<<<< Output >>>>>"
          - "{{ GrafanaOutput }}"
        verbosity: 0
# Tags
  tags:
    - crtGrafana
#################################################
#
# ansible-playbook ./pb.mgmtHomeInfrastructure.yml --extra-vars "v_role=promgraf" --tags crtPromNodeExp
#
#################################################
- name: Create node exporter container task
  block:
    - name: Create node exporter container section
      containers.podman.podman_container:
        name: c_promnodeexp
        image: docker.io/prom/node-exporter
        hostname: svr-promne
        volumes:
          - /proc:/host/proc:ro
          - /sys:/host/sys:ro
          - /:/rootfs:ro
        ports:
          - 9100:9100
        network:
          - promgraf_net
        # env:
        #   MARIADB_RANDOM_ROOT_PASSWORD: 'yes'
        debug: false
        restart_policy: on-failure:3
        state: started
      register: PromNodeExpOutput
    - name: Print PromNodeExpOutput
      debug:
        msg:
          - "<<<<< Output >>>>>"
          - "{{ PromNodeExpOutput }}"
        verbosity: 0
# Tags
  tags:
    - crtPromNodeExp
#################################################
#
# ansible-playbook ./pb.mgmtHomeInfrastructure.yml --extra-vars "v_role=promgraf" --tags crtPromNodeExp
#
#################################################
- name: Create blackbox exporter container task
  block:
    - name: Create blackbox exporter container section
      containers.podman.podman_container:
        name: c_promblackboxexp
        image: docker.io/prom/blackbox-exporter
        hostname: svr-prombb
        etc_hosts:
          ubqt-udm.home.lcl: 192.168.1.1
          svr-symcon.home.lcl: 192.168.1.204
          svr-rbm.hom.lcl: 192.168.1.202
          svr-toolz.home.lcl: 192.168.1.210
          svr-esxi.home.lcl: 192.168.1.200
        command:
          - '--config.file=/blackbox.yml'
        volumes:
          - /home/myadmin/ansible/roles/mgmt_PrometheusGrafana/files/blackbox.yml:/blackbox.yml:ro
        ports:
          - 9115:9115
        debug: false
        restart_policy: on-failure:3
        state: started
      register: PromBlackBoxOutput
    - name: Print PromBlackBoxOutput
      debug:
        msg:
          - "<<<<< Output >>>>>"
          - "{{ PromBlackBoxOutput }}"
        verbosity: 0
# Tags
  tags:
    - crtPromBlackBoxExp

