download_url: https://galaxy.ansible.com/api/v3/plugin/ansible/content/published/collections/artifacts/pureport-fabric-1.0.0.tar.gz
format_version: 1.0.0
name: fabric
namespace: pureport
server: https://galaxy.ansible.com/api/
signatures: []
version: 1.0.0
version_url: /api/v3/plugin/ansible/content/published/collections/index/pureport/fabric/versions/1.0.0/
