---
# tasks file for mgmt_FilesDirs
#
# Author: Walter Karl
# Date: December.2023
# Company:
#
# TODO: task to copy init-mongo.js to svr-unifi
#
#################################################
# ansible-playbook ./pb.mgmtHomeInfrastructure.yml --limit svr-unifi --extra-vars "v_role=files" --tags cpRmt2Lcl
#################################################
- name: Copy remote to local task
  block:
    - name: Get files in backup folder
      ansible.builtin.find:
        paths: "/root/container/c_unifi/config/data/backup/autobackup/"
        patterns: '*.unf'
      register: FilesFound
    - name: Print FilesFound
      debug:
        msg:
          - "<<<<< FilesFound >>>>>"
          - "{{ FilesFound }}"
        verbosity: 2
    - name: Get newest file
      ansible.builtin.set_fact:
        NewestFile: "{{ (FilesFound.files | sort(attribute='mtime') | last).path }}"    
    - name: Print NewestFile
      debug:
        msg:
          - "<<<<< NewestFile >>>>>"
          - "{{ NewestFile }}"
        verbosity: 2
    - name: Copy remote to local section
      ansible.builtin.fetch:
        src: "{{ NewestFile }}"
        dest: ./FILES.BUP/
        flat: true
        owner: myadmin
        group: myadmin
        mode: '0600' 
      register: FilesCopy
    - name: Print FilesCopy
      debug:
        msg:
          - "<<<<< FilesCopy >>>>>"
          - "{{ FilesCopy }}"
        verbosity: 2
  tags:
    - cpRmt2Lcl
#################################################
# ansible-playbook ./pb.mgmtHomeInfrastructure.yml --limit svr-toolz --extra-vars "v_role=files ansible_become=false" --tags pshGitHub
# TODO: problem with relative path
#################################################
- name: Push to GitHub task
  block:
    - name: Check git status section
      ansible.builtin.shell: git status
      args:
        chdir: "{{ ansible_user_dir }}/ansible/"
      when:
        - ansible_user_id == "myadmin"
      register: GitStatus
    - name: Print GitStatus
      debug:
        msg:
          - "<<<<< GitStatus >>>>>"
          - "{{ GitStatus }}"
        verbosity: 2
    - name: Push to GitHub section
      ansible.builtin.command:
        cmd: "{{ item }}"
      loop:
        - git add *
        - git commit -m "automated commit"
        - git push -u ongithub master
      args:
        chdir: "{{ ansible_user_dir }}/ansible/"
      when:
        - '"staged" in GitStatus.stdout'
        - ansible_user_id == "myadmin"
      register: GitPushOutput
    - name: Print GitPushOutput
      debug:
        msg:
          - "<<<<< GitPushOutput >>>>>"
          - "{{ GitPushOutput }}"
        verbosity: 2
  # Tags
  tags:
    - pshGitHub
