---
# tasks file for mgmt_FilesDirs
#
# Author: Walter Karl
# Date: December.2023
# Company:
#
# TODO: task to copy init-mongo.js to svr-unifi
#
#################################################
# ansible-playbook ./pb.mgmtHomeInfrastructure.yml -l svr-unifi --extra-vars "v_role=files" --tags cpRmt2Lcl
#################################################
- name: Copy remote to local task
  block:
    - name: Get files in backup folder
      ansible.builtin.find:
        paths: "/root/container/c_unifi/config/data/backup/autobackup/"
        patterns: '*.unf'
      register: FilesFound
    - name: Print FilesFound
      debug:
        msg:
          - "<<<<< FilesFound >>>>>"
          - "{{ FilesFound }}"
        verbosity: 2
    - name: Get newest file
      ansible.builtin.set_fact:
        NewestFile: "{{ (FilesFound.files | sort(attribute='mtime') | last).path }}"    
    - name: Print NewestFile
      debug:
        msg:
          - "<<<<< NewestFile >>>>>"
          - "{{ NewestFile }}"
        verbosity: 2
    - name: Copy remote to local section
      ansible.builtin.fetch:
        src: "{{ NewestFile }}"
        dest: /home/myadmin/ansible/FILES.BUP/
        flat: true
        owner: myadmin
        group: myadmin
        mode: '0600' 
  tags:
    - cpRmt2Lcl
